# Generated by Django 2.1.4 on 2019-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabuser',
            name='gitlab_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
