# Generated by Django 2.1.7 on 2019-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190226_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabuser',
            name='gitlab_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
