#sudo: false
dist: xenial
language: python
cache: pip
git:
    depth: 1
python:
    - "3.5"
    - "3.6"
    - "3.7"
env:
    - DJANGO="2.0"
    - DJANGO="2.1"
    - DJANGO="2.2"
    - DJANGO="master"

matrix:
    fast_finish: true
    exclude:
        - python: "3.5"
          env: DJANGO="master"
    allow_failures:
        - env: DJANGO="2.2" # Locally is working
        - env: DJANGO="master"
before_install:
    - pip install --upgrade pip
install:
    - pip install tox-travis
script:
    - tox
after_success:
    - pip install coveralls
    - coveralls
