# Generated by Django 2.1.7 on 2019-03-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabuser',
            old_name='auth_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gitlabuser',
            old_name='social_auth',
            new_name='user_social_auth',
        ),
    ]
