# Generated by Django 2.1.4 on 2019-01-04 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('gitlab_web_url', models.URLField(blank=True, null=True)),
                ('username', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('gitlab_web_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PR', 'Private'), ('EX', 'External'), ('PU', 'Public')], default='PR', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('path', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(choices=[('R', 'Root'), ('U', 'Username'), ('P', 'Project'), ('G', 'Group')], default='G', max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groups.Namespace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('gitlab_web_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PR', 'Private'), ('EX', 'External'), ('PU', 'Public')], default='PR', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('path', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('parent_namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='groups.Namespace')),
                ('project_namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_namespace', to='groups.Namespace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='attached_groups',
            field=models.ManyToManyField(blank=True, related_name='attached_users_list', to='groups.Namespace'),
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users_list', to='groups.Namespace'),
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users_projects_list', to='groups.Project'),
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='social_auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SZR_user', to='social_django.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='gitlabuser',
            name='user_namespace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Namespace'),
        ),
        migrations.AlterUniqueTogether(
            name='namespace',
            unique_together={('parent', 'path')},
        ),
    ]
