# Generated by Django 2.1.7 on 2019-03-29 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('django_celery_beat', '0006_periodictask_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('execute_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(4, 'Waiting'), (0, 'Ready'), (1, 'Running'), (2, 'Succeed'), (3, 'Failed')], default=0)),
                ('error_msg', models.CharField(blank=True, max_length=2000, null=True)),
                ('access_level', models.IntegerField(choices=[(10, 'Guest'), (20, 'Reporter'), (30, 'Developer'), (40, 'Master'), (50, 'Owner')], default=10)),
                ('username', models.CharField(max_length=100)),
                ('celery_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask')),
                ('new_gitlab_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GitlabUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks_addmember', to='core.GitlabUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('execute_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(4, 'Waiting'), (0, 'Ready'), (1, 'Running'), (2, 'Succeed'), (3, 'Failed')], default=0)),
                ('name', models.CharField(max_length=2000)),
                ('tasks_number', models.PositiveIntegerField(default=0)),
                ('finished_tasks_number', models.PositiveIntegerField(default=0)),
                ('failed_task_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddSubgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('execute_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(4, 'Waiting'), (0, 'Ready'), (1, 'Running'), (2, 'Succeed'), (3, 'Failed')], default=0)),
                ('error_msg', models.CharField(blank=True, max_length=2000, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('public', 'Public')], default='private', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('path', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('celery_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddSubgroupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('execute_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(4, 'Waiting'), (0, 'Ready'), (1, 'Running'), (2, 'Succeed'), (3, 'Failed')], default=0)),
                ('name', models.CharField(max_length=2000)),
                ('tasks_number', models.PositiveIntegerField(default=0)),
                ('finished_tasks_number', models.PositiveIntegerField(default=0)),
                ('failed_task_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GitlabGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('gitlab_web_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='addsubgroupgroup',
            name='gitlab_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GitlabGroup'),
        ),
        migrations.AddField(
            model_name='addsubgroupgroup',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_task_group_addsubgroupgroup', to='groups.AddSubgroup'),
        ),
        migrations.AddField(
            model_name='addsubgroup',
            name='new_gitlab_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GitlabGroup'),
        ),
        migrations.AddField(
            model_name='addsubgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks_addsubgroup', to='core.GitlabUser'),
        ),
        migrations.AddField(
            model_name='addsubgroup',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_set', to='groups.AddSubgroupGroup'),
        ),
        migrations.AddField(
            model_name='addmembergroup',
            name='gitlab_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GitlabGroup'),
        ),
        migrations.AddField(
            model_name='addmembergroup',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_task_group_addmembergroup', to='groups.AddSubgroup'),
        ),
        migrations.AddField(
            model_name='addmember',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_set', to='groups.AddMemberGroup'),
        ),
    ]
