# Generated by Django 2.1.7 on 2019-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgroupmembertask',
            name='access_level',
            field=models.IntegerField(choices=[(10, 'Guest'), (20, 'Reporter'), (30, 'Developer'), (40, 'Master'), (50, 'Owner')], default=10),
        ),
        migrations.AddField(
            model_name='addgroupmembertask',
            name='error_msg',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
