# Generated by Django 2.1.4 on 2019-01-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabuser',
            name='attached_groups',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='social_auth',
        ),
        migrations.RemoveField(
            model_name='gitlabuser',
            name='user_namespace',
        ),
        migrations.AlterUniqueTogether(
            name='namespace',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='namespace',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent_namespace',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_namespace',
        ),
        migrations.DeleteModel(
            name='GitlabUser',
        ),
        migrations.DeleteModel(
            name='Namespace',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
