# Generated by Django 2.1.7 on 2019-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190319_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgroupmembertaskgroup',
            name='name',
            field=models.CharField(blank=True, default='%(class)s', max_length=2000, null=True),
        ),
    ]
