# Generated by Django 2.1.7 on 2019-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_addgroupmembertaskgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgroupmembertaskgroup',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
