# Generated by Django 2.1.7 on 2019-03-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190328_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgroupmembertaskgroup',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_task_group_addgroupmembertaskgroup', to='groups.AddGroupMemberTaskGroup'),
        ),
    ]
